name: Build API Binaries
run-name: Build API Binaries

concurrency:
  group: "Build API Binaries"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
    branches:
      - 'main'

env:
  AZURE_WEBAPP_PACKAGE_PATH: './'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
    steps:
      - uses: actions/checkout@v4

      # Load NuGetCache
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles(env.AZURE_WEBAPP_PACKAGE_PATH) }}
          
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish --configuration Release --no-build --output ${{env.DOTNET_ROOT}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: binaries_${{github.sha}}
          path: ${{env.DOTNET_ROOT}}/publish