name: Build MyWorkID Binaries
run-name: Build MyWorkID Binaries

concurrency:
  group: "Build MyWorkID Binaries"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-binaries-reusable.yml
