name: Build Frontend Binaries
run-name: Build Frontend Binaries

concurrency:
  group: "Build Frontend Binaries"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

env:
  WORKING_DIRECTORY: "./frontend/myaccount-vnext-frontend"
  NPM_CACHE_DEPENDENCY_PATH: "frontend/myaccount-vnext-frontend/package-lock.json"
  NODE_VERSION: "18.x"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIRECTORY}}
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ${{ env.NPM_CACHE_DEPENDENCY_PATH }}
      - name: install npm modules
        run: npm ci
      - name: npm build
        run: CI=false npm run build
      - name: Display structure
        run: ls -R
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: ${{env.WORKING_DIRECTORY}}/build