name: Deploy API
run-name: Deploy API

concurrency:
  group: "Deploy API"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

env:
  AZURE_WEBAPP_NAME : ${{ vars.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_PACKAGE_PATH: './backend/src/c4a8.MyAccountVNext.API/c4a8.MyAccountVNext.API'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
    steps:
      - uses: actions/checkout@v4

      # Load NuGetCache
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles(env.AZURE_WEBAPP_PACKAGE_PATH) }}
          
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish --configuration Release --no-build --output ${{env.DOTNET_ROOT}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/publish

  fetch_environments:
    runs-on: ubuntu-latest
    permissions:
      actions: read
    outputs:
      environments: ${{ steps.get_environments.outputs.ENVIRONMENTS }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - id: get_environments
        name: Get Environments
        run: |
          ENVIRONMENTS_RAW="$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/c4a8-devstudio/c4a8-myaccount-vnext/environments | jq -r ".environments[].name" | jq -c -Rn '[inputs]')"
          echo "ENVIRONMENTS=$ENVIRONMENTS_RAW" >> $GITHUB_OUTPUT
          echo "ENVIRONMENTS=$ENVIRONMENTS_RAW" >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: 
      - build
      - fetch_environments
    strategy:
      matrix:
        environment: ${{ fromJson(needs.fetch_environments.outputs.ENVIRONMENTS) }}
    permissions:
      contents: none
      id-token: write
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
      # logout from Azure
      - name: logout
        run: |
          az logout
