name: 'Test CI'

on:
  pull_request:

env:
  DOTNET_CORE_VERSION: 8.0.x

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Build
        run: |
          dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: |
          dotnet test --logger "trx;LogFileName=test-results.trx"
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: test-results.trx